### 开发环境配置信息
server.port: 9000
### 如果需要激活多个属性，中间用逗号分隔，主要在环境配置做条件时使用，如swagger生产环境不开放等
#spring.profiles.active: common,dev
spring.profiles.active: common

### xxl-job db
xxl.job.db:
   driverClass: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/xxl-job?useUnicode=true&characterEncoding=UTF-8&useSSL=false
   user: xxljobuser  #建议对xxl-job使用单独的用户管理，xxljobuser需要select ,update,insert,delete权限。因为一般情况下生产用户是不能有delete删除操作权限的
   password: 123456

### xxl-job email
xxl.job.mail:
   host: smtp.xyz.cn
   port: 25
   username: monitor@xyz.cn
   password: passw0rd
   sendNick: 《任务调度平台》

### xxl-job login
xxl.job.login:
   username: admin
   password: 123456

### xxl-job, access token
xxl.job.accessToken:

### xxl-job, i18n (default empty as chinese, "en" as english)
xxl.job.i18n:



