##
### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
#xxl.job.admin.addresses=http://127.0.0.1:7701/xxl-job-admin
xxl.job.admin.addresses: http://127.0.0.1:9000

### xxl-job executor address
xxl.job:
  executor:
    appname: xxl-job-executor-yooeee-sample
    ip:
    port: 9999
    logpath: /data/applogs/xxl-job/yooeee-jobhandler
    logretentiondays: -1
  accessToken: